### ISSUE TITLE
能否增加一个回答问题的开关？

### ISSUE THREAD

**Issue by sk163** [yetone/bob-plugin-openai-translator#12]
在翻译和回答问题进行切换，这样就省了别的客户端了

**Comment by yetone** [comment]
谢谢建议，我考虑一下如何实现

**Comment by nevertoday** [comment]
同样， 能不能给自定义前置提问中prompt 我有多prompt 并不是只有翻译这一个需求~

**Comment by g199209** [comment]
我做了个增强版，不知道作者会不会合入：

**Comment by g199209** [comment]
我做了个增强版，不知道作者会不会合入：
https://github.com/yetone/bob-plugin-openai-translator/pull/48

**Comment by liby** [comment]
https://github.com/yetone/bob-plugin-openai-translator/releases/tag/v0.4.0
