### ISSUE TITLE
【需求】请问后续打算支持chrome插件吗

### ISSUE THREAD

**Issue by Zhang21** [yetone/bob-plugin-openai-translator#13]
大佬好，请问后续打算支持chrome插件形式的翻译吗？

不是mac系统，用不了这个翻译插件。

之前使用的是 [翻译侠（Translate Man）](https://chrome.google.com/webstore/detail/translate-man/fapgabkkfcaejckbfmfcdgnfefbmlion)这个翻译插件。

**Comment by yetone** [comment]
感谢你的建议，我考虑支持一下

**Comment by withuan** [comment]
您好，希望能出相应的Chrome插件

**Comment by yetone** [comment]
正在开发中

**Comment by yetone** [comment]
@Zhang21 @withuan @ourines 已经支持 Chrome 插件，欢迎使用！

https://github.com/yetone/openai-translator

**Comment by ernestyao** [comment]
> @Zhang21 @withuan @ourines 已经支持 Chrome 插件，欢迎使用！
> 
> https://github.com/yetone/openai-translator

没研究过插件和脚本的差异机制啊，从泛用性的角度说，能不能考虑油猴脚本这种？这样是跨平台的，甚至可以用Adguard安装，同时跨多浏览器

**Comment by Zhang21** [comment]
done!
