### ISSUE TITLE
中翻英出现未知错误

### ISSUE THREAD

**Issue by Ukenn2112** [yetone/bob-plugin-openai-translator#2]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/60847880/219993283-b6749e09-c7dd-4cc7-93e6-59d9afe2912b.png">
翻译长字符复现率 100%

**Comment by ymyz1229** [comment]
我英译汉也出现“未知错误”

**Comment by yetone** [comment]
OpenAI 的 API 抖动导致的，你可以下载 0.0.3 再试一下

**Comment by Ukenn2112** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/60847880/220030010-74eef2f8-e1e5-47a2-be73-fd0af5087607.png">
还是有类似情况，主要是在翻译段落时根本就没有加载进度而是直接就跳出未知错误

**Comment by yetone** [comment]
@Ukenn2112 找到原因了，你升级到 0.0.4 试一下呢？

**Comment by Ukenn2112** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/60847880/220038079-edcdfa3e-305f-473f-9db3-89de2ae671d0.png">
这次有了错误 log

**Comment by yetone** [comment]
@Ukenn2112 这是 OpenAI 的限制了，无法解。感觉 OpenAI 太不稳定 + 太慢 + 限制很多，所以还是不适合做翻译 API，打算 archive 掉这个项目了

**Comment by yetone** [comment]
@Ukenn2112 感谢支持！刚刚更新了 0.0.5 版本，你可以再试一下

**Comment by Ukenn2112** [comment]
> @Ukenn2112 感谢支持！刚刚更新了 0.0.5 版本，你可以再试一下

ok 它现在正常了！
