### ISSUE TITLE
支持代理设置

### ISSUE THREAD

**Issue by onesecurity** [yetone/bob-plugin-openai-translator#20]
RT，希望支持代理或者自定义API设置，最近API很不稳定

**Comment by TeachMeJavaTonight** [comment]
可能是被墙原因，现在未知错误了。

**Comment by shawnbow** [comment]
我看了一下Bob的API，感觉HTTP的API没有支持Proxy的能力，可能需要Bob升级才可以了，或者只能用全局代理了。

**Comment by yetone** [comment]
请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题，感谢 @Ukenn2112 的贡献！

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1206493/222943314-d748872f-a92f-4b51-815a-a9ae70568b60.png">

**Comment by jayleecn** [comment]
> 请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题，感谢 @Ukenn2112 的贡献！
> 
> <img alt="image" width="1037" src="https://user-images.githubusercontent.com/1206493/222943314-d748872f-a92f-4b51-815a-a9ae70568b60.png">

太棒了！可以直接用0.2.4替换自己手工改的版本了。辛苦辛苦！

**Comment by onesecurity** [comment]
> 请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题，感谢 @Ukenn2112 的贡献！
> 
> <img alt="image" width="1037" src="https://user-images.githubusercontent.com/1206493/222943314-d748872f-a92f-4b51-815a-a9ae70568b60.png">

tks
