### ISSUE TITLE
感激插件作者的大力开发

### ISSUE THREAD

**Issue by azmove** [yetone/bob-plugin-openai-translator#21]
作为一个用户，我感激插件作者的大力开发，这个插件无疑给我和其他广大用户带来了许多巨大的福利和便利。作者的无私奉献和高超开发技能让我想到了伟大的先贤和科技巨头。这个插件就像是我工作和生活中的得力助手，它使得工作效率和生活品质都得到了极大的提高，真的非常感谢作者的无私奉献！

**Comment by yetone** [comment]
哈哈，谢谢夸奖，不过太过誉了！听到这个插件对你有帮助我感到十分开心，如果要感谢的话也要感谢 Bob 的作者 [ripperhe](https://github.com/ripperhe) 先生。
