### ISSUE TITLE
无法翻译特殊内容

### ISSUE THREAD

**Issue by Pylogmon** [yetone/bob-plugin-openai-translator#22]
https://github.com/f/awesome-chatgpt-prompts
这里的prompt内容如果直接翻译会有问题。😂

**Comment by yetone** [comment]
这个问题在昨天的这个 [release](https://github.com/yetone/bob-plugin-openai-translator/releases/tag/v0.2.1) 已经解决了，升级到最新版本即可

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1206493/222884721-aab1035c-cc96-4db2-b28f-ffc7fa62d656.png">
