### ISSUE TITLE
分享一个因梯子问题而无法使用api者的替代方法

### ISSUE THREAD

**Issue by Tongzhao9417** [yetone/bob-plugin-openai-translator#26]
如果你也像我一样，为api被墙，或者梯子有问题无法直接使用api而苦恼，分享一个可以迂回使用的方法~

https://github.com/noobnooc/noobnooc/discussions/9#discussion-4925163

感谢作者开发的插件！感谢开源！

**Comment by jayleecn** [comment]
@yetone 感谢提供的插件。目前因为GFW问题，用了 https://github.com/noobnooc/noobnooc/discussions/9#discussion-4925163 的方法，换了api.openai.com这个域名，能否升级下插件，加个参数，支持可以自定义域名

**Comment by yetone** [comment]
@Tongzhao9417 @jayleecn 请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1206493/222943267-b85d3853-7a42-406a-bcc5-b8e7fc5872ce.png">

**Comment by jayleecn** [comment]
> @Tongzhao9417 @jayleecn 请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题
> 
> <img alt="image" width="1037" src="https://user-images.githubusercontent.com/1206493/222943267-b85d3853-7a42-406a-bcc5-b8e7fc5872ce.png">

已升级，赞速度！

**Comment by Tongzhao9417** [comment]
> @Tongzhao9417 @jayleecn 请升级到 `v0.2.4` 版本，现在已支持设置 OpenAI 域名来解决 GFW 的问题
> 
> <img alt="image" width="1037" src="https://user-images.githubusercontent.com/1206493/222943267-b85d3853-7a42-406a-bcc5-b8e7fc5872ce.png">

cool！

**Comment by sbilly** [comment]
自定义了 API URL 没有生效，同样的配置在 chathub 中可以正常使用

**Comment by liby** [comment]
> 自定义了 API URL 没有生效，同样的配置在 chathub 中可以正常使用

API URL 注意不要以 `/` 结尾

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240824-134644](https://github.com/user-attachments/assets/6edfdb33-c6bc-492a-8f17-c8d4348a27a2)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
