### ISSUE TITLE
chrome 插件复制完kpi key 之后就没反应了

### ISSUE THREAD

**Issue by dipixiaoliumang** [yetone/bob-plugin-openai-translator#27]
是被墙了吗，我用的clash for windows 选的全局代理。复制完kpi key 之后点了save 之后没反应了就

**Comment by tidong1** [comment]
解决了吗  我也遇到相同问题

**Comment by liby** [comment]
请参阅[使用方法](https://github.com/yetone/bob-plugin-openai-translator/tree/main#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
