### ISSUE TITLE
“未知错误”

### ISSUE THREAD

**Issue by ivan509-hub** [yetone/bob-plugin-openai-translator#28]
这里出现了“未知错误”，不知道是因为网络问题还是API？

如果是网络问题的是，我登录网页版是OK的，只是在使用插件的时候显示未知错误。
![CleanShot 2023-03-06 at 10 41 38](https://user-images.githubusercontent.com/60826937/223007277-9e2baaca-79b8-4669-8b87-d6a78531054f.png)

**Comment by ivan509-hub** [comment]
应该就是网络问题，我刚刚测试了下DEEPL，也是同样的提示。

**Comment by ivan509-hub** [comment]
现在DEEPL的没有问题，速度还挺快的。
![CleanShot 2023-03-06 at 11 28 08](https://user-images.githubusercontent.com/60826937/223013004-28de7c42-90dd-4a5b-834c-ba03d1b000a4.png)

**Comment by victor-crypto** [comment]
我已经复现（刚好碰到）该issue
原因：
应该是你的代理软件将api.openai.com指向了不能用的路线，导致报错。我自己用的是mac surge，代理规则将api.openai.com指向了美国线路，结果该线路无法使用。
<img width="995" alt="image" src="https://user-images.githubusercontent.com/24761742/225225552-ebb9b5bb-59f0-4db1-8ac3-c302d46096da.png">

解决办法：
给api.openai.com手动添加一个规则，指向可以使用的线路。
<img width="984" alt="CleanShot 2023-03-15 at 14 32 52@2x" src="https://user-images.githubusercontent.com/24761742/225225688-c13096a6-219a-41cd-b295-b09c39e7be63.png">

**Comment by ivan509-hub** [comment]
哇 谢谢谢 我研究下 怎么在clash X里面操作

**Comment by Chuan-10** [comment]
@ivan509-hub 请问您研究出如何在clash里面操作了吗

**Comment by ivan509-hub** [comment]
没有诶 我就换了个节点 就可以了 估计是之前的节点出现问题了
________________________________
发件人: Chuan-10 ***@***.***>
发送时间: 2023年3月25日 11:13
收件人: yetone/bob-plugin-openai-translator ***@***.***>
抄送: Ivan ***@***.***>; Mention ***@***.***>
主题: Re: [yetone/bob-plugin-openai-translator] “未知错误” (Issue #28)


@ivan509-hub<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fivan509-hub&data=05%7C01%7C%7C79096fd8ea9541b70d8908db2cdef5b0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638153108356784560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8h4xuDuFrda0VdOUDcE5BlBk0azMxTl15CTu5iR6ZQ%3D&reserved=0> 请问您研究出如何在clash里面操作了吗

―

**Comment by liby** [comment]
[如果你们需要 ChatGPT/OPENAI 的代理规则（来源不记得了）：](https://twitter.com/taresky/status/1641085318781874182)

```
# ChatGPT
DOMAIN-SUFFIX,[http://openai.com](https://t.co/bFNscwS7jx),OPENAI // ChatGPT
DOMAIN-SUFFIX,[http://openaiapi-site.azureedge.net](https://t.co/xXSR2SAEtl),OPENAI // ChatGPT
DOMAIN-SUFFIX,[http://identrust.com](https://t.co/W3qWZuR2ul),OPENAI // ChatGPT
DOMAIN-SUFFIX,[http://auth0.com](https://t.co/CIMvsbJXCS),OPENAI // ChatGPT
```
