### ISSUE TITLE
About instructing chat models

### ISSUE THREAD

**Issue by liby** [yetone/bob-plugin-openai-translator#29]
**这个 issue 旨在探讨指导 model 作为翻译引擎的最佳实践**

以下是我的一点点想法，欢迎讨论。

现在的相关实现如下：
```
if (isChatGPTModel) {
        body.messages = [
            { role: "system", content: prompt },
            { role: "user", content: `"${query.text}"` },
        ];
    }
```

看似是遵循了文档中的例子和描述：
> Typically, a conversation is formatted with a system message first, followed by alternating user and assistant messages.
> The system message helps set the behavior of the assistant ...
> Many conversations begin with a system message to gently instruct the assistant

但如果继续往下面翻到 [Instructing chat models](https://platform.openai.com/docs/guides/chat/instructing-chat-models) 部分，又会看到它有提到说：
> [In general, `gpt-3.5-turbo-0301` does not pay strong attention to the system message, and therefore important instructions are often better placed in a user message.](https://platform.openai.com/docs/guides/chat/instructing-chat-models#:~:text=In%20general%2C%20gpt%2D3.5%2Dturbo%2D0301%20does%20not%20pay%20strong%20attention%20to%20the%20system%20message%2C%20and%20therefore%20important%20instructions%20are%20often%20better%20placed%20in%20a%20user%20message.)

所以我在想，是不是改成下面这样，更合理一些：
```
if (isChatGPTModel) {
        body.messages = [
            // { role: "system", content: "You are a translation engine."  },
            { role: "system", content: "I'm a translation engine."  },
            { role: "user", content: `"${prompt}: ${query.text}"` },
        ];
    }
```

不过我自己在 [Playgroud](https://platform.openai.com/playground/p/default-grammar?mode=chat&model=gpt-3.5-turbo-0301) 试了一下，没有发现太明显的区别，不知道是不是例子过于简单的缘故

**Comment by simonwu53** [comment]
的确是个改进方向。可以试试我这个例子，ChatGPT完全忽略了翻译而是回应了文本中的要求😂

<img width="473" alt="Screenshot 2023-03-06 at 13 42 00" src="https://user-images.githubusercontent.com/27355570/223104006-1ede158c-cc95-4b45-b7c9-3bfc8233e5da.png">

**Comment by yetone** [comment]
@simonwu53 试了一下，的确有效！我基于 @liby 的 prompt 稍微加了点限制，你这个 bad case 就解决了！十分感谢！

我已经 release 了新版本，可以升级一下

https://github.com/yetone/bob-plugin-openai-translator/commit/786ebdd735a9745135185f8308da80f6a7e303e0#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R55

https://github.com/yetone/bob-plugin-openai-translator/commit/786ebdd735a9745135185f8308da80f6a7e303e0#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R55

**Comment by simonwu53** [comment]
@yetone @liby  感谢大家🙏🏻！

**Comment by Songkeys** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/22665058/223118083-35bca13c-0aa7-4d6f-a283-cf68206c19a1.png">

https://twitter.com/zty0826/status/1632468826137972736

我们能处理好这种情况吗？

**Comment by yetone** [comment]
@Songkeys 要不把这个图片删掉？我怕这个项目被消失 🥲

**Comment by liby** [comment]
> 我们能处理好这种情况吗？

评论里有提到：
> 有人提到，随机化的对用户隐藏的EOS，如果GPT能理解到这个是最高优先级，那就可能可以

单纯的在 prompt 中加分隔符，比如 `===`、`###`、`"""` 是没什么用的，避免不了有人故意这样做，还徒增 token 消耗

**Comment by Songkeys** [comment]
> 避免不了有人故意这样做

确实。既然 bob 插件是用户自己使用，应该不需要考虑这种故意的注入问题？但我不知道会不会有实际 case 出现这种情况，虽然目前我还没发现。
