### ISSUE TITLE
关于非英语的支持

### ISSUE THREAD

**Issue by realsiao** [yetone/bob-plugin-openai-translator#3]
你好，请问该插件是否可以对非英语进行翻译？
<img width="885" alt="image" src="https://user-images.githubusercontent.com/119853210/220707520-03325f36-692a-4390-98af-c2361d137202.png">

**Comment by yetone** [comment]
感谢建议，我准备加上

**Comment by yetone** [comment]
已支持俄语，请升级到 v0.0.10

**Comment by realsiao** [comment]
谢谢！
