### ISSUE TITLE
不同语种英语的情况

### ISSUE THREAD

**Issue by okisdev** [yetone/bob-plugin-openai-translator#32]
中文有不同语种，所以也想试一下英语能不能切换不同语种输出。

稍微验证了一下，发现各种各样的 prompt 好像都不能解决问题。

## 验证

尝试将`en`更改成`en-GB`、`British English`或者`UK English`发现都解决不了这个问题，即使得出的结果是 **(Note: this translation is in British English)**，实际上翻译出来的句子都还是美式英语。（如果只针对于单词进行翻译，有时倒是可以翻译成选定语种，但大部分情况下还是美式）

![CleanShot_2023-03-06_14 10 00@2x](https://user-images.githubusercontent.com/66008528/223141621-d997814a-54c9-49c2-a3b9-5d14b2250be4.png)
![CleanShot_2023-03-06_14 12 59@2x](https://user-images.githubusercontent.com/66008528/223142435-f398af03-9805-4b7d-ad36-d08871f3fc98.png)

## 预期结果

`Visualisation`是英式写法，而`Visualization`是美式写法，在 DeepL 中的语种是正确的。

![CleanShot_2023-03-06_15 15 28@2x](https://user-images.githubusercontent.com/66008528/223151434-b38d0de6-c71e-4b14-b859-34d63d77931d.png)
![CleanShot_2023-03-06_15 18 44@2x](https://user-images.githubusercontent.com/66008528/223152340-d0931460-10cf-4988-8fa2-e2cc4f8b85d6.png)

**Comment by simonwu53** [comment]
试试只用“British”？

我用这个prompt可以翻译：
[SRC] 可视化是一个是利用计算机图形学 和图像处理技术 ， 将数据转换成图形或图像在屏幕上显示出来 ， 并进行交互处理的理论 、 方法和技术 [TGT] British

**Comment by okisdev** [comment]
@simonwu53 刚刚试了一下，还是不能完美解决这个问题。

如图，在一段句子中包括多个需要英式英语语境中，只有部分被转换为英式英语。

* 🫥 `Visualization` -> `Visualisation`
* 🫥 `colors` -> `colours`
* ✅ `trousers`

![CleanShot_2023-03-06_18 55 40@2x](https://user-images.githubusercontent.com/66008528/223204577-8d8eb7d8-d932-47cc-b5a4-9343b4304f35.png)

**Comment by simonwu53** [comment]
又试了一下，好像用“British spelling”可以成功让它理解意图。提示词工程真的是很重要啊😂，也可以直接一步步问他要怎样说它才能明白。

以下是我直接用助手模式问的，没有用system指令让它成为translator：
![955238A3-25E1-49C9-8AF5-B167256B3060](https://user-images.githubusercontent.com/27355570/223229030-1a9357a1-4999-46b6-b424-6922d422f818.jpeg)
![A794D251-BB00-4241-96EF-B0616E92AD39](https://user-images.githubusercontent.com/27355570/223229039-6ef040bc-0312-465a-8277-7ba47154f8bb.jpeg)
