### ISSUE TITLE
选中翻译显示Open AI接口相应错误

### ISSUE THREAD

**Issue by ShrewdJean** [yetone/bob-plugin-openai-translator#37]
显示 You exceeded your current quota, please check your plan and billing details. 请问是为啥，有人遇到这个问题吗
<img width="480" alt="Screen Shot 2023-03-07 at 10 39 50 AM" src="https://user-images.githubusercontent.com/95852606/223305952-52e68d09-5719-4526-b920-b23500a83900.png">

**Comment by akl7777777** [comment]
这大概是余额不足了

**Comment by ShrewdJean** [comment]
Open AI余额不足吗？ 我才翻译第一条😂

**Comment by Achernar-Eridani** [comment]
我也遇到这个错误了，我还是chatGPT Plus

**Comment by yetone** [comment]
你的使用量已经超过了 OpenAI API 的免费额度，请购买 token 数：https://platform.openai.com/account/usage

@Achernar-Eridani ChatGPT plus 跟 OpenAI API 是不同的东西

**Comment by yetone** [comment]
@ShrewdJean 可以到 OpenAI 官网看一下额度使用情况 https://platform.openai.com/account/usage

**Comment by ShrewdJean** [comment]
@yetone 谢谢！所以这个API得充值才能用是吧，了解了

**Comment by wanglavender** [comment]
我的Open AI显示的没有用过额度，但还是在翻译的时候出现“接口相应错误”。是因为没有买Pop么
<img width="853" alt="image" src="https://user-images.githubusercontent.com/32957837/223860310-47a98eb4-3cbe-4b2f-911c-90cf8d5d7c0c.png">
