### ISSUE TITLE
接口响应错误

### ISSUE THREAD

**Issue by xzbdmw** [yetone/bob-plugin-openai-translator#41]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/97848247/223416643-520bb666-3ccf-4d96-a06d-0da71b718e69.png">

**Comment by cruxim** [comment]
我也遇到了这个问题，频繁接口相应错误

**Comment by cruxim** [comment]
而且我的梯子是没有问题的，所以完全不懂是什么原因。

**Comment by xzbdmw** [comment]
> 而且我的梯子是没有问题的，所以完全不懂是什么原因。

可以了,vpn开全局

**Comment by cruxim** [comment]
> > 而我的梯子是没有问题的，所以完全不懂是什么原因。
> 
> 可以了,vpn开启全局

我是一阵一阵的，用的小火箭，一直用的“配置”也就是全局，但偶尔就崩一下，这会儿我也好了，不知道是不是open AI今天服务器不稳定（挠头

**Comment by xzbdmw** [comment]
> > > 而我的梯子是没有问题的，所以完全不懂是什么原因。
> > 
> > 
> > 可以了,vpn开启全局
> 
> 我是一阵一阵的，用的小火箭，一直用的“配置”也就是全局，但偶尔就崩一下，这会儿我也好了，不知道是不是open AI今天服务器不稳定（挠头

yes 可能真是不稳定 我关了全局也可以了

**Comment by xzbdmw** [comment]
> > > 而我的梯子是没有问题的，所以完全不懂是什么原因。
> > 
> > 
> > 可以了,vpn开启全局
> 
> 我是一阵一阵的，用的小火箭，一直用的“配置”也就是全局，但偶尔就崩一下，这会儿我也好了，不知道是不是open AI今天服务器不稳定（挠头

yes 可能真是不稳定 我关了全局也可以了

**Comment by liby** [comment]
应该与代理服务器有关，可以考虑使用[ Cloudflare Workers 实现代理 OpenAI API](https://twitter.com/noobnooc/status/1631856756774277120)
