### ISSUE TITLE
是否能够增加代理配置 和 代理验证功能

### ISSUE THREAD

**Issue by BrowLi** [yetone/bob-plugin-openai-translator#42]
是否能够增加代理配置，目前选中openai translate 无法响应

**Comment by BrowLi** [comment]
最好再增加一个验证代理的功能

**Comment by liby** [comment]
更推荐[使用 Cloudflare Workers 实现代理 OpenAI API 的](https://twitter.com/noobnooc/status/1631856756774277120)
