### ISSUE TITLE
润色功能不正常

### ISSUE THREAD

**Issue by paohuoche** [yetone/bob-plugin-openai-translator#44]
<img width="399" alt="截屏2023-03-08 11 47 43" src="https://user-images.githubusercontent.com/7116988/223614769-fa1e8ec2-17b6-4078-8446-c8f4926bf3a7.png">

**Comment by jermyn626** [comment]
@paohuoche 我这边好像没问题，版本是 0.2.6

<img width="400" alt="image" src="https://user-images.githubusercontent.com/18393754/223693047-f5124145-116e-4bba-b93a-0ddcb06c6b3d.png">

**Comment by paohuoche** [comment]
> @paohuoche 我这边好像没问题，版本是 0.2.6
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/18393754/223693047-f5124145-116e-4bba-b93a-0ddcb06c6b3d.png">

我当时是0.2.5，现在升级到0.2.6 是没问题了。谢谢。
