### ISSUE TITLE
日语支持问题

### ISSUE THREAD

**Issue by jianghao-zhang** [yetone/bob-plugin-openai-translator#5]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/81921082/221776214-10b63fbd-6f23-428a-b4f6-1a6e4d2f2a95.png">
似乎不支持日语翻译? 请问大大能不能修改一下Prompts？

**Comment by yetone** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1206493/221781177-6a589a6b-b672-4958-b273-c81931e0e59b.png">

我这边是可以翻译日文的，你的日文原文是什么？我来调试一下

**Comment by jianghao-zhang** [comment]
> <img alt="image" width="492" src="https://user-images.githubusercontent.com/1206493/221781177-6a589a6b-b672-4958-b273-c81931e0e59b.png">
> 
> 我这边是可以翻译日文的，你的日文原文是什么？我来调试一下

嘘を真実の様に売りつけるのは三流のペテン師です。
嘘を真実に変えるのは二流のペテン師です。
嘘を真実に変えて、世界すらも変えてしまうのが一流のペテン師です

**Comment by yetone** [comment]
@jianghao-zhang 现在可以了，你升级一下插件即可

**Comment by jianghao-zhang** [comment]
辛苦大大了
