### ISSUE TITLE
希望可以添加语境信息

### ISSUE THREAD

**Issue by VsentKB** [yetone/bob-plugin-openai-translator#53]
可以在插件配置里添加一项用户可自定义的语境信息插入到message中，这样可以做到自己定义某些专有名词的翻译以及优化翻译的准确性。
例如：
{"role": "system", "content": "你现在正在翻译的是一篇学术论文请注意专有名词和用语。"}

**Comment by liby** [comment]
考虑到使用场景比较小众，暂时 Close 了
