### ISSUE TITLE
...Bob popclip用一个功能要下三个软件

### ISSUE THREAD

**Issue by coobaker** [yetone/bob-plugin-openai-translator#54]
666

**Comment by YooboH** [comment]
popclip又不是必须的，不就一个bob吗，本来就是bob的插件没bob不是搞笑吗

**Comment by YooboH** [comment]
> 666
popclip又不是必须的，就一个bob，本来就是bob的插件没bob不是搞笑吗

**Comment by YooboH** [comment]
> 666

popclip又不是必须的，就一个bob，本来就是bob的插件没bob不是搞笑吗
