### ISSUE TITLE
Windows用户遇到问题：“You exceeded your current quota, please check your plan and billing details.”

### ISSUE THREAD

**Issue by Brian-Deng** [yetone/bob-plugin-openai-translator#58]
如题，下载了桌面版，但是用不了，似乎无法解决

**Comment by Brian-Deng** [comment]
![image](https://user-images.githubusercontent.com/18079806/224999822-7d29449d-1a2a-46ee-95c6-63816ace1a19.png)

**Comment by adinxu** [comment]
https://fanyi.youdao.com/

**Comment by akl7777777** [comment]
你超过了你当前的配额，请检查你的计划和计费细节

**Comment by liby** [comment]
Please transfer to https://github.com/yetone/openai-translator
