### ISSUE TITLE
非常好用的插件！请尽快支持GPT-4！

### ISSUE THREAD

**Issue by Rexlambert** [yetone/bob-plugin-openai-translator#60]
非常好用的插件！请尽快支持GPT-4！全面替代我的其他谷歌翻译插件。等GPT翻译插件很久了，我还给BOB作者留言，一直都没开发，好在你们做出来了！感谢！

**Comment by 343arbiter** [comment]
是的！非常希望作者能把插件这边也更新一下，因为还是离不开bob的语音合成和ocr（鞠躬，但这个bob已经很牛了

**Comment by Rexlambert** [comment]
语音合成是什么功能？我还没用过，用得最多的就是截图翻译，效率飞起～写论文，学习，ppt都是超级好用

**Comment by Ennall** [comment]
gpt-4的接口openai还没全面开放，需要排队申请。

**Comment by liby** [comment]
已经支持 https://github.com/yetone/bob-plugin-openai-translator/releases/tag/v0.2.7

另外需要确保你已经申请到 GPT-4 的资格
