### ISSUE TITLE
会自动加载发音、例句等，浪费token，希望可以手动关闭掉

### ISSUE THREAD

**Issue by LNMWR** [yetone/bob-plugin-openai-translator#63]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/104123146/227103260-a019fc31-d494-4bfb-857b-27faabcec672.png">

如图，并不需要发音和例句但是自动加载了，看了设置里面没有相关选项可以关闭

**Comment by liby** [comment]
Please transfer to https://github.com/yetone/openai-translator
