### ISSUE TITLE
作者还打算把另一个项目的特性同步到这个插件来吗

### ISSUE THREAD

**Issue by wiidede** [yetone/bob-plugin-openai-translator#64]
毕竟习惯用bob了，现在这个插件好久没更新，另一边疯狂更新😂

**Comment by letsfkccp** [comment]
我也习惯Bob，希望能更新这个插件。另外从中国以外的地区打赏作者的微信和支付宝不可用，想支持一下。

From: 小的的 DeDe ***@***.***>
Date: Thursday, March 23, 2023 at 7:52 AM
To: yetone/bob-plugin-openai-translator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yetone/bob-plugin-openai-translator] 作者还打算把另一个项目的特性同步到这个插件来吗 (Issue #64)

毕竟习惯用bob了，现在这个插件好久没更新，另一边疯狂更新😂

**Comment by xiajinchun** [comment]
+1

**Comment by 343arbiter** [comment]
+1 对bob实在过于依赖了……

**Comment by kaneruan** [comment]
+1

**Comment by letsfkccp** [comment]
+1

From: youma ***@***.***>
Date: Thursday, March 30, 2023 at 8:40 PM
To: yetone/bob-plugin-openai-translator ***@***.***>
Cc: letsfkccp ***@***.***>, Comment ***@***.***>
Subject: Re: [yetone/bob-plugin-openai-translator] 作者还打算把另一个项目的特性同步到这个插件来吗 (Issue #64)

+1

―

**Comment by liby** [comment]
后续我会帮忙维护，有功能需求可以提 ticket，也欢迎大家直接 PR 🥰
