### ISSUE TITLE
我找不到私钥文件

### ISSUE THREAD

**Issue by yuxigod** [yetone/bob-plugin-openai-translator#67]
哪个是私钥文件啊？我用的chrome浏览器安装这个插件
![屏幕截图 2023-03-29 055022](https://user-images.githubusercontent.com/82942217/228376203-e712d608-fd98-458b-bcd3-9405b18a25af.png)

**Comment by liby** [comment]
请参阅[使用方法](https://github.com/yetone/bob-plugin-openai-translator/tree/main#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
