### ISSUE TITLE
拖拽进去安装时显示加载扩展程序出错

### ISSUE THREAD

**Issue by yuxigod** [yetone/bob-plugin-openai-translator#68]
为什么会这样呢？我是拖到chrome里安装的
![屏幕截图 2023-03-29 061002](https://user-images.githubusercontent.com/82942217/228378327-62f716da-bfdb-40ae-9d17-81cceebb9a6b.png)

**Comment by littleprince361** [comment]
me too

**Comment by liby** [comment]
请参阅[使用方法](https://github.com/yetone/bob-plugin-openai-translator/tree/main#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
