### ISSUE TITLE
能否让翻译的内容实时显示

### ISSUE THREAD

**Issue by life404** [yetone/bob-plugin-openai-translator#69]
考虑到网络的问题，如果翻译较长的段落，需要等待较长的时间才能看到结果。能否像桌面版的客户端一样实时输出翻译结果，进一步提升使用的体验

**Comment by xzbdmw** [comment]
+1

**Comment by love1017best** [comment]
流式输出应该能极大改善体验

**Comment by liby** [comment]
[需要等待上游 Bob 支持](https://github.com/ripperhe/Bob/issues/451)

**Comment by liby** [comment]
Duplicate of #15
