### ISSUE TITLE
请问可否支持Azure接口？

### ISSUE THREAD

**Issue by LingweiMeng** [yetone/bob-plugin-openai-translator#70]
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-python

**Comment by liby** [comment]
[已经支持了](https://github.com/yetone/bob-plugin-openai-translator/pull/62)

需要发个版，cc @yetone

**Comment by liby** [comment]
Resolved https://github.com/yetone/bob-plugin-openai-translator/releases/tag/v0.2.7
