### ISSUE TITLE
接口响应错误 - You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by gakkiyomi** [yetone/bob-plugin-openai-translator#71]
![image](https://user-images.githubusercontent.com/41406557/229401910-8f40b03b-3aa9-412f-b9e2-a1a28f768deb.png)

**Comment by academic-waste** [comment]
也遇到了这个问题

**Comment by academic-waste** [comment]
你的API到期了

**Comment by skymagician** [comment]
我也遇到这个问题了，换了api也不行。

**Comment by WangJiHyo** [comment]
确实更新API也不行

**Comment by skymagician** [comment]
api 用完了，要么花钱买，要么注册一个新号。我注册了一个新号，现在恢复了。

**Comment by WangJiHyo** [comment]
奇怪 我的没用完啊 别处也用这个接口一切正常的

**Comment by liby** [comment]
> 奇怪 我的没用完啊 别处也用这个接口一切正常的

打开 https://platform.openai.com/account/usage，可以看到是否过期
