### ISSUE TITLE
[Bug] {{TypeError: undefined is not an object (evaluating 'apiKeys.split')}}

### ISSUE THREAD

**Issue by Eridium1** [yetone/bob-plugin-openai-translator#77]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/bob-plugin-openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

0.3.1

### 系统版本 | System version

macOS 13.2.1

### Bob version

Bob 1.5.0

### 复现步骤 | Reproduce step

<img width="975" alt="image" src="https://user-images.githubusercontent.com/111474042/231338060-10d0b36c-5740-466a-b441-19ec8744abd3.png">

### 你看到了什么错误？What errors do you see?

请问出现 TypeError: undefined is not an object (evaluating 'apiKeys.split') 应该怎么解决

### 你期望看到什么？What did you expect to see?

解决: TypeError: undefined is not an object (evaluating 'apiKeys.split')

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by woodypeckerwho** [comment]
You can try to solve this problem by generating a new API key.

**Comment by liby** [comment]
Resolved https://github.com/yetone/bob-plugin-openai-translator/commit/4f870284c127fd51cfa8694abe3dc11d78725827

v0.3.2 会检查用户是否正确填写了 API Keys，并在未填写时给出报错
