### ISSUE TITLE
[Feature] “可选性翻译”

### ISSUE THREAD

**Issue by Jesse-0x** [yetone/bob-plugin-openai-translator#78]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Feature

增加新的一个按钮或者其他东西，控制是否使用OpenAI去翻译。

### 描述 Motivation

因为有些时候会遇到钱钱不够或者文字数量比较大不想翻译的情况，又不是很想每次翻译之前都打开再关上。不知道可不可以实现特定字符翻译或者点击按钮翻译（如果允许的话）。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Jesse-0x** [comment]
https://github.com/yetone/openai-translator

**Comment by Jesse-0x** [comment]
https://github.com/yetone/openai-translator

**Comment by letsfkccp** [comment]
Bob就有这个功能
增加新的一个按钮或者其他东西，控制是否使用OpenAI去翻译。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by liby** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/38807139/232972750-cb1a2828-fde5-4781-9f51-3f0db86d7cc9.png">
