### ISSUE TITLE
期望功能

### ISSUE THREAD

**Issue by stnaw** [yetone/bob-plugin-openai-translator#8]
已经有了OpenAI版本的翻译，是不是有可能再加个基于OpenAI的语法检查插件？哈哈

**Comment by yetone** [comment]
哈哈，正有此意！全面替代 DeepL 和 Grammarly！
<img width="932" alt="image" src="https://user-images.githubusercontent.com/1206493/222381651-2a33a48e-540b-4199-b37f-a60281acce62.png">

**Comment by yetone** [comment]
现在 `v0.2.0` 已支持给句子润色和语法检查的功能！
