### ISSUE TITLE
[自定义 Prompt]

### ISSUE THREAD

**Issue by ethan-ih** [yetone/bob-plugin-openai-translator#80]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Feature

允许使用自定义的 Prompt 来对 Bob 输入的内容进行加工。

### 描述 Motivation

我使用 ai 对阅读材料提问，生成抽认卡片。有时候也使用这个改写等等，Bob 可以直接对内容进行处理，结合 Openai 的 API 将无比丝滑。

### 还有其他内容吗？Anything else?

我看到隔壁 freechatgpt 这个插件支持自定义 Prompt ，但他们的不能用自己的 API (速度有点慢)，所以希望开发大大能支持一下。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
https://github.com/yetone/bob-plugin-openai-translator/releases/tag/v0.4.0
