### ISSUE TITLE
增加打字机输出的效果

### ISSUE THREAD

**Issue by iwoov** [yetone/bob-plugin-openai-translator#81]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Feature

增加打字机输出的效果，类似插件和桌面版的效果

### 描述 Motivation

在bob插件中，翻译的结果是等待很久后一次性输出的，能否增加打字机的效果，文字一个个输出呢？

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
Duplicate of #15
