### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by LYZ10** [yetone/bob-plugin-openai-translator#9]
开发者大大您好，请问windows用户能有办法使用上吗？真的很需要呢，谢谢。

**Comment by yetone** [comment]
感谢支持，我想想办法🤔️

**Comment by LYZ10** [comment]
如果window是用户也能用上这么好的工具，一定是件很有幸福感的事。
感谢您百忙中的回复，祝一切安好！

**Comment by LYZ10** [comment]
如果window是用户也能用上这么好的工具，一定是件很有幸福感的事。
感谢您百忙中的回复，祝一切安好！

**Comment by liby** [comment]
https://github.com/yetone/openai-translator
